### ISSUE TITLE
離散フーリエ変換について

### ISSUE THREAD

**Issue by hoy11111** [mmorise/beginning_asa#1]
初めまして
私は今、matlabで離散フーリエ変換をfft関数などを使わずにプログラムを書いています。「dft_size×dft_size の行列」と「dft_size×1 の行列」の積により DFT 計算を行うプログラムを書きたいのですが上手く書けなくて困っています。

下記プログラムの
X_real=zeros(dft_size,1);
X_imag=zeros(dft_size,1);のX_real=zeros()内を(dft_size,dft_size)に変えて、
scriptファイルの
A=zeros(dft_size,1);
T=zeros(dft_size,1);のA()内を(dft_size,dft_size)に書き換えればよいと思ったのですが、上手くいきませんでした。

アドバイスを頂けたら幸いです。

以下、プログラムリスト
//////
# DFT.m
function [X_real,X_imag]=DFT(x_real,x_imag,dft_size)
X_real=zeros(dft_size,1);
X_imag=zeros(dft_size,1);
for k=1:dft_size,
for n=1:dft_size,
w_real=cos(-2*pi*(k-1)*(n-1)/dft_size);
w_imag=sin(-2*pi*(k-1)*(n-1)/dft_size);
X_real(k,1)=X_real(k,1)+w_real*x_real(n,1)-w_imag*x_imag(n,1);
X_imag(k,1)=X_imag(k,1)+w_real*x_imag(n,1)+w_imag*x_real(n,1);
end
end
////////
# script.m
clear;
dft_size=60;
x_real=audioread('test.wav',[1 dft_size]);
x_imag=zeros(dft_size,1);
[X_real,X_imag]=DFT(x_real,x_imag,dft_size);
A=zeros(dft_size,1);
T=zeros(dft_size,1);
frequency=zeros(dft_size,1);
for k=1:dft_size,
A(k,1)=sqrt(X_real(k,1)*X_real(k,1)+X_imag(k,1)*X_imag(k,1));
T(k,1)=atan(X_imag(k,1)/X_real(k,1));
frequency(k,1)=k-1;
end
subplot(2,1,1);
stem(frequency,A);
subplot(2,1,2);
stem(frequency,T);

**Comment by mmorise** [comment]
アドバイスということでしたら，現状のコードが複素数の書き方も冗長になっているので，
- MATLABは複素数をそのまま使えるので使うこと（x = 1 + 1i * 2のように書ける）
- MATLABにおける*演算子は行列の掛け算を意味すること
- X = w * x;という形でDFTが実現できるので，この形に持っていくためのwというdft_size×dft_sizeの行列を作ること
の3点でしょうか．関連するコードが書籍中にありますので，そちらをご覧頂ければある程度ヒントになると思います．

**Comment by hoy11111** [comment]
ご返答ありがとうございます。
アドバイスしてくださった、複素数をそのまま使える点と*演算子がMATLABでは行列の掛け算を意味することについて理解できました。

ただ、3つ目の行列を作ることに関しては作ることは分かったのですが、どう言う形でどこに記述するのか分からなくて詰まってしまいました。

お手間を取らせてしまい本当に申し訳ないのですが、
『X = w * x;という形でDFTが実現できるので，この形に持っていくためのwというdft_size×dft_sizeの行列を作ることという』のはどこの記述を変えれば良いのか教えて欲しいです。

**Comment by mmorise** [comment]
記述を変えるというよりは，DFTの関数全般を書き換えることになります．行列演算としてのX = w * x;で結果が得られるようにwを作るので，DFT関数内は(1) wを作る, (2) X = w * x;計算する流れになります．wの作り方は*の演算が何を意味しているかを理解することになり，その次は実質答えになりますので，ヒントとしてはこの辺が限界です．書籍の3.4節にコードのヒントもありますので，3章を読みながらチェックすると良いでしょう．

**Comment by hoy11111** [comment]
返信が遅くなりましてすいません。
まだ冗長ではあるプログラムですが、アドバイスを参考に完成させることができました。
ご指導していただきありがとうございました。

以下、プログラムリスト
# DFT.m
function [X_real,X_imag]=DFT(x_real,x_imag,dft_size)
X_real=zeros(dft_size,1);
X_imag=zeros(dft_size,1);
w_real=zeros(dft_size,dft_size);
w_imag=zeros(dft_size,dft_size);
for k=1:dft_size,
for n=1:dft_size,
w_real(k,n)=cos(-2*pi*(k-1)*(n-1)/dft_size);
w_imag(k,n)=sin(-2*pi*(k-1)*(n-1)/dft_size);
end
end
X_real=w_real*x_real-w_imag*x_imag;
X_imag=w_real*x_imag+w_imag*x_real;

**Comment by hoy11111** [comment]
ありがとうございました
